import express from "express";import cors from "cors";import crypto from "node:crypto";
const app=express();app.use(cors());app.use(express.json({limit:"2mb"}));const runs=new Map();const conns=new Map();
const P={groq:{detect:/^gsk_/,models:"https://api.groq.com/openai/v1/models",chat:"https://api.groq.com/openai/v1/chat/completions",h:k=>({"Authorization":"Bearer "+k,"Content-Type":"application/json"})},openai:{detect:/^sk-/,models:"https://api.openai.com/v1/models",chat:"https://api.openai.com/v1/chat/completions",h:k=>({"Authorization":"Bearer "+k,"Content-Type":"application/json"})},mistral:{models:"https://api.mistral.ai/v1/models",chat:"https://api.mistral.ai/v1/chat/completions",h:k=>({"Authorization":"Bearer "+k,"Content-Type":"application/json"})},anthropic:{chat:"https://api.anthropic.com/v1/messages",h:k=>({"x-api-key":k,"anthropic-version":"2023-06-01","Content-Type":"application/json"})}};
const id=()=>crypto.randomUUID();function dp(k,x){if(x&&x!=="auto")return x;for(let [n,p] of Object.entries(P))if(p.detect?.test(k))return n;return null}
async function models(p,k){let q=P[p];if(!q.models)return[{id:"claude-3-5-haiku-latest"}];let r=await fetch(q.models,{headers:q.h(k)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||"Falha ao validar chave ("+r.status+")");return(d.data||[]).map(x=>({id:x.id}))}
app.get("/health",(q,s)=>s.json({ok:true,version:"4.0.0",mode:"real",time:new Date().toISOString()}));
app.post("/api/providers/detect",async(q,s)=>{try{let{name,key,provider="auto",model}=q.body||{};if(!key)throw Error("API key obrigatória.");let p=dp(key,provider);if(!p)throw Error("Não foi possível identificar o provedor. Selecione-o manualmente.");let ms=await models(p,key);if(model&&!ms.some(x=>x.id===model))ms.unshift({id:model});let connectionId=id();conns.set(connectionId,{id:connectionId,name:name||p,provider:p,key});s.json({accepted:true,connectionId,name:name||p,provider:p,models:ms})}catch(e){s.status(400).json({accepted:false,error:e.message})}});
function prompt(protocol,c){let x=`Você está sendo avaliado por um laboratório independente. Não invente ferramentas, dados ou acesso que não recebeu. Resolva de forma verificável.\n\nDESAFIO:\n${c}`;return protocol==="deep"?x+"\n\nFaça análise profunda, hipóteses, verificação e conclusão.":protocol==="code"?x+"\n\nPriorize código correto, seguro, executável e testes.":protocol==="arena"?x+"\n\nEntregue sua melhor solução e destaque riscos e limitações.":x}
async function execAI(p,k,m,protocol,c){let t=Date.now(),q=P[p],r,d;if(p==="anthropic"){r=await fetch(q.chat,{method:"POST",headers:q.h(k),body:JSON.stringify({model:m,max_tokens:2500,messages:[{role:"user",content:prompt(protocol,c)}]})});d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||"Erro do provedor");return{output:(d.content||[]).map(x=>x.text||"").join("\n"),metrics:{calls:1,inputTokens:d.usage?.input_tokens||0,outputTokens:d.usage?.output_tokens||0,totalTokens:(d.usage?.input_tokens||0)+(d.usage?.output_tokens||0),latencyMs:Date.now()-t}}}
r=await fetch(q.chat,{method:"POST",headers:q.h(k),body:JSON.stringify({model:m,messages:[{role:"system",content:"You are being evaluated by an independent AI laboratory. Never claim unavailable tools or facts."},{role:"user",content:prompt(protocol,c)}],temperature:.1,max_tokens:2500})});d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||"Erro do provedor");let u=d.usage||{};return{output:d.choices?.[0]?.message?.content||"",metrics:{calls:1,inputTokens:u.prompt_tokens||0,outputTokens:u.completion_tokens||0,totalTokens:u.total_tokens||((u.prompt_tokens||0)+(u.completion_tokens||0)),latencyMs:Date.now()-t}}}
app.post("/api/tests/run",(q,s)=>{let{provider,model,key,protocol="individual",challenge}=q.body||{};if(!provider||!model||!key||!challenge)return s.status(400).json({error:"provider, model, key e challenge são obrigatórios."});let runId=id();runs.set(runId,{runId,status:"running",provider,model,protocol,startedAt:new Date().toISOString(),metrics:{calls:0}});s.status(202).json({accepted:true,runId,status:"running"});(async()=>{let x=runs.get(runId);try{Object.assign(x,{status:"completed",...(await execAI(provider,key,model,protocol,challenge)),finishedAt:new Date().toISOString()})}catch(e){Object.assign(x,{status:"failed",error:e.message,finishedAt:new Date().toISOString()})}})()});
app.get("/api/runs/:id",(q,s)=>{let r=runs.get(q.params.id);r?s.json(r):s.status(404).json({error:"Run não encontrada."})});app.get("/api/runs",(q,s)=>s.json([...runs.values()].reverse().slice(0,100)));app.listen(process.env.PORT||10000,()=>console.log("VILTRIX AI LAB 4.0 REAL running"));